mapping:
  - factors: [N=12, M=1, K=1]
    permutation: [K, M, N]
    target: DRAM
    type: temporal
  - factors: [N=4, M=32, K=1]
    permutation: [K, M, N]
    target: PE
    type: spatial
  - factors: [N=1, M=1, K=3072]
    permutation: [K, M, N]
    target: Buffer
    type: temporal
  - factors: [N=16, M=4, K=1]
    permutation: [N, M, K]
    target: Accelerator
    type: spatial
    split: 1
